export interface Product {
  id: number
  attributes: {
    createdAt: string
    name: string
    description: string
    sale_price: number
    images: StrapiFile[]
  }
}

// Generated by https://quicktype.io

export interface StrapiFile {
  data: Datum[]
}

export interface Datum {
  id: number
  attributes: Attributes
}

export interface Attributes {
  name: string
  alternativeText: string
  caption: string
  width: number
  height: number
  formats: Formats
  hash: string
  ext: string
  mime: string
  size: number
  url: string
  previewUrl: null
  provider: string
  provider_metadata: null
  createdAt: string
  updatedAt: string
}

export interface Formats {
  small: Medium
  medium: Medium
  thumbnail: Medium
}

export interface Medium {
  ext: string
  url: string
  hash: string
  mime: string
  name: string
  path: null
  size: number
  width: number
  height: number
}
